version: '2.0'
services:
  web:
    build: .
    command: python /code/api/app.py
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
     - db
  db:
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: mypassword
       MYSQL_DATABASE: mydatabase

  
