web:
  build: .
  command: python /code/api/app.py
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
   - db
  hostname: myapirest
db:
  hostname: myapirest
  image: orchardup/mysql
  environment:
     MYSQL_ROOT_PASSWORD: mypassword
     MYSQL_DATABASE: mydatabase
