Vagrant.configure("2") do |config|

	azure.tenant_id = ENV['AZURE_TENANT_ID']
	azure.client_id = ENV['AZURE_CLIENT_ID']
	azure.client_secret = ENV['AZURE_CLIENT_SECRET']
	azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

  config.vm.define "maquinaAPImiga" do |serviceObject|
    serviceObject.vm.box = 'azure'

    serviceObject.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceObject.vm.provider :azure do |azure, override|

      azure.location="westeurope"

      azure.resource_group_name="groupMiga"
      azure.vm_name="maquinaAPImiga"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

    end
  end

  config.vm.define "maquinaDBmiga" do |serviceImage|
    serviceImage.vm.box = 'azure'

    serviceImage.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceImage.vm.provider :azure do |azure, override|

      azure.location="westeurope"

      azure.resource_group_name="groupMiga"
      azure.vm_name="maquinaDBmiga"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

    end
  end

  #Provisión
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "provision"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  end
end