Vagrant.configure("2") do |config|
  config.vm.define "maquinaAPImiga" do |serviceObject|
    serviceObject.vm.box = 'azure'

    serviceObject.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceObject.vm.provider :azure do |azure, override|
      #Set a territory
      azure.location="westeurope"

      azure.resource_group_name="groupMiga"
      azure.vm_name="maquinaAPImiga"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    end
  end

  config.vm.define "maquinaDBmiga" do |serviceImage|
    serviceImage.vm.box = 'azure'

    serviceImage.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceImage.vm.provider :azure do |azure, override|
      #Set a territory
      azure.location="westeurope"

      azure.resource_group_name="groupMiga"
      azure.vm_name="maquinaDBmiga"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    end
  end
end