Vagrant.configure("2") do |config|
  config.vm.define "maquinaAPImiga" do |serviceObject|
    serviceObject.vm.box = 'azure'

    serviceObject.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceObject.vm.provider :azure do |azure, override|
      #Set a territory
      azure.location="westeurope"

      azure.resource_group_name="groupMiga"
      azure.vm_name="maquinaAPImiga"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

      azure.tenant_id = '0e71855c-01cb-481c-bf99-1986f84f2260'
      azure.client_id = 'azure-cli-2017-12-10-22-42-25'
      azure.client_secret = '4489be7d-de5e-43ca-9e41-0389e5184ec2'
      azure.subscription_id = '7735cd7f-4893-4ff1-91e4-3f3b6c95536e'
    end
  end

  config.vm.define "maquinaDBmiga" do |serviceImage|
    serviceImage.vm.box = 'azure'

    serviceImage.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceImage.vm.provider :azure do |azure, override|
      #Set a territory
      azure.location="westeurope"

      azure.resource_group_name="groupMiga"
      azure.vm_name="maquinaDBmiga"

      azure.vm_image_urn="Canonical:UbuntuServer:16.04-LTS:latest"

      azure.tenant_id = '0e71855c-01cb-481c-bf99-1986f84f2260'
      azure.client_id = 'azure-cli-2017-12-10-22-47-35'
      azure.client_secret = '2eef373b-edd3-4edf-8a07-23ae8034dca8'
      azure.subscription_id = '7735cd7f-4893-4ff1-91e4-3f3b6c95536e'
    end
  end
end